allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ramz001-cinema/contracts'
  - '@ramz001-cinema/passport'
  - '@ramz001-cinema/core'
  - js-yaml@3.15.0 || 5.2.2
  - brace-expansion@5.0.8
overrides:
  baseline-browser-mapping@>=2.0.0 <2.11.0: ^2.11.0
  browserslist@<=4.28.6: ^4.28.7
  js-yaml@>=3.0.0 <3.15.1: ^3.15.1
  js-yaml@>=3.0.0 <3.15.2: ^3.15.2
  js-yaml@>=5.0.0 <=5.2.1: ^5.2.2
